# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Programming\Python\Goblin_drilling_v.2.2\Lib\site-packages\QtDesigner\Settings_drilling_modes.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings_drilling_modes(object):
    def setupUi(self, Settings_drilling_modes):
        Settings_drilling_modes.setObjectName("Settings_drilling_modes")
        Settings_drilling_modes.resize(475, 91)
        Settings_drilling_modes.setMinimumSize(QtCore.QSize(400, 90))
        Settings_drilling_modes.setSizeIncrement(QtCore.QSize(500, 90))
        self.layoutWidget = QtWidgets.QWidget(Settings_drilling_modes)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 461, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_select_file = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_select_file.sizePolicy().hasHeightForWidth())
        self.pushButton_select_file.setSizePolicy(sizePolicy)
        self.pushButton_select_file.setObjectName("pushButton_select_file")
        self.horizontalLayout.addWidget(self.pushButton_select_file)
        self.label_select_file = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_select_file.sizePolicy().hasHeightForWidth())
        self.label_select_file.setSizePolicy(sizePolicy)
        self.label_select_file.setObjectName("label_select_file")
        self.horizontalLayout.addWidget(self.label_select_file)
        self.layoutWidget1 = QtWidgets.QWidget(Settings_drilling_modes)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 40, 131, 42))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_type_cogalm = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_type_cogalm.setObjectName("radioButton_type_cogalm")
        self.verticalLayout.addWidget(self.radioButton_type_cogalm)
        self.radioButton_type_bashneft = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_type_bashneft.setObjectName("radioButton_type_bashneft")
        self.verticalLayout.addWidget(self.radioButton_type_bashneft)

        self.retranslateUi(Settings_drilling_modes)
        QtCore.QMetaObject.connectSlotsByName(Settings_drilling_modes)

    def retranslateUi(self, Settings_drilling_modes):
        _translate = QtCore.QCoreApplication.translate
        Settings_drilling_modes.setWindowTitle(_translate("Settings_drilling_modes", "Настройки"))
        self.pushButton_select_file.setText(_translate("Settings_drilling_modes", "Выбрать файл"))
        self.label_select_file.setText(_translate("Settings_drilling_modes", "Выберите суточную сводку"))
        self.radioButton_type_cogalm.setText(_translate("Settings_drilling_modes", "Когалымская сводка"))
        self.radioButton_type_bashneft.setText(_translate("Settings_drilling_modes", "Башкирская сводка"))
